//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.ORMPractice.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class departments_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public departments_tb()
        {
            this.positions_tb = new HashSet<positions_tb>();
        }
    
        public int idDepartment { get; set; }
        public string departmentName { get; set; }
        public string departmentDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<positions_tb> positions_tb { get; set; }
    }
}
