//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.ORMPractice.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class positions_tb
    {
        public int idPosition { get; set; }
        public int idDepartment { get; set; }
        public string positionName { get; set; }
        public string positionDescription { get; set; }
    
        public virtual departments_tb departments_tb { get; set; }
    }
}
